### ISSUE TITLE
Error with latest v1.7.6 docker image (container does not start)

### ISSUE THREAD

**Issue by SmartPhoneLover** [borgmatic-collective/docker-borgmatic#206] opened 2023-02-05 19:52 UTC
I would like to report an issue with the latest 1.7.6 docker image.

When updated, it fails to start, showing the following log from terminal output:
![4664674](https://user-images.githubusercontent.com/42898749/216841574-c76dcb5a-c1ad-47b4-a7d0-91bb93ef781f.PNG)

The previous 1.7.5 works well.

**Comment by grantbevis** [comment] 2023-02-06 08:20
Could you please post your docker-compose with sensitive information removed? Also double check that you are mapping your `crontab.txt` correctly.

**Comment by SmartPhoneLover** [comment] 2023-02-06 12:23
I don't have a stack installation, but in unRAID. Anyway, the cmd that is run in the background when the container is created is the following:
`/usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker create --name='borgmatic' --net='bridge' -e TZ="Europe/Paris" -e HOST_OS="Unraid" -e HOST_HOSTNAME="SPL-NAS-BKP" -e HOST_CONTAINERNAME="borgmatic" -e 'TZ'='Europe/Madrid' -e 'PUID'='99' -e 'PGID'='100' -l net.unraid.docker.managed=dockerman -l net.unraid.docker.icon='https://github.com/witten/borgmatic/raw/master/docs/static/borgmatic.png' -v '/mnt/remotes/':'/mnt/bkp_from-data':'ro' -v '/mnt/user/backups/repos':'/mnt/bkp_to-repos':'rw' -v '/mnt/user/backups/cache':'/root/.cache/borg':'rw' -v '/mnt/user/appdata/borgmatic/config':'/etc/borgmatic.d':'rw' -v '/mnt/user/appdata/borgmatic/borg_keys':'/root/.config/borg':'rw' -v '/mnt/user/appdata/borgmatic/ssh_keys':'/root/.ssh':'rw' -v '':'/mnt/fuse':'rw,shared' --device='/dev/fuse' --cap-add SYS_ADMIN 'b3vis/borgmatic:1.7.5'`

Another user has the same error.

By the other hand, I don't use cronjob inside the container. I automate the execution of the scripts (I interact with borg not borgmatic) externally.

**Comment by grantbevis** [comment] 2023-02-06 13:05
So the problem is you not having a crontab.txt the container won't start without one as it tries to test the crontab.txt is valid. 

I don't understand why you would define the container as a 'long running' container within the unRAID UI then interact with it through scripts. You'll be better off just writing your script/docker-compose to do `docker-compose run borgmatic $command` than your current way.

Or just setup the crontab.txt inside the borgmatic container and let it manage it for you

**Comment by modem7** [comment] 2023-02-22 08:21
Closing ticket as no reply in 2 weeks. 

Please let us know if you're still having the issue after following @grantbevis's suggestion.

**Closed by modem7** 2023-02-22 08:21 UTC
Labels: question

**Comment by SmartPhoneLover** [comment] 2023-02-22 12:17
After creating a blank crontab file in the corresponding location it's working as expected.
Updated to the latest 1.7.7 image.

Thank you! And sorry for not replying before.

**Comment by grantbevis** [comment] 2023-02-22 12:27
Good suggestion @SmartPhoneLover
